[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
verbose = true
exclude = '''
/(
  | \.git
  | \.mypy_cache
  | dist
  | \.pants\.d
  | virtualenvs
  | \.venv
  | _build
  | build
  | dist
  | snapshots
)/
'''

[tool.isort]
line_length = 120
skip = '.terraform'
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
known_third_party = 'aws_lambda_powertools,boto3,botocore,pytest,snapshottest'
known_first_party = 'events,notify_slack'
indent = '    '

[tool.mypy]
namespace_packages = true
explicit_package_bases = true

no_implicit_optional = true
implicit_reexport = false
strict_equality = true

warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true

pretty = true
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true

[tool.coverage.run]
branch = true
omit = ["*_test.py", "tests/*", "events/*", "messages/*", "snapshots/*", "venv/*", ".mypy_cache/*", ".pytest_cache/*"]

[tool.coverage.report]
show_missing = true
skip_covered = true
skip_empty = true
sort = "-Miss"
fail_under = 75
